exclude:
  - "Gemini_Generated_Image_5dl5sr5dl5sr5dl5.png"
  - "LEIA-ME.md"
  - "Plataforma de Cálculo Trabalhista.png"
  - "Plataforma de Dimensionamento de Climatização.png"
  - "Plataforma de Estimativa de Reformas.png"
  - "README.md"
  - "brasil.png"
  - "calculadora-confeiteira.png"
  - "espanha.png"
  - "estados-unidos.png"
  - "index-old.html"
  - "logo-tema-escuro-horizontal-2.png"
  - "mapa-calculadoras.zip"
  - "mapa-favicon.jpg"
  - "mapa-favicon.png"
  - "mapa-main.zip"
  - "o-que-fazemos.png"
  - "sala-reuniao-mapa.png"
  - "site-escritorio-advocacia.png"
  - "site-para-floricultura.png"
  - "site-tenis.png"
  - "tech-font.jpg"
  - "tecnologia-font.jpg"
  - "video-para-canal-drone.png"
  - "video-para-mercado-imobiliario.png"
  - "video-para-youtube.png"
  - "Claude outputs"
